export const projects = [
	{
		technologies: [],
		_id: "1",
		title: "Capstone Project",
		image: "./Prestige.PNG",
		description: "",
		link: "/",
	},
	{
		technologies: [],
		_id: "2",
		title: "Epiblog",
		image: "./Epiblog.PNG",
		description: "",
		link: "/",
	},
	{
		technologies: [],
		_id: "3",
		title: "LibriEpici",
		image: "./Libriepici.PNG",
		description: "",
		link: "/",
	},
	{
		technologies: [],
		_id: "4",
		title: "Anason Shoes",
		image: "./AnasonShoes.PNG",
		description: "",
		link: "/",
	},
	{
		technologies: [],
		_id: "5",
		title: "Nasflix",
		image: "./NasoFlix.PNG",
		description: "",
		link: "/",
	},
];
